/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PasswordResetRouteImport } from './routes/password-reset'
import { Route as GdprRightsRouteImport } from './routes/gdpr-rights'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as DeleteDataRouteImport } from './routes/delete-data'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityPostIdRouteImport } from './routes/community.$postId'
import { Route as ApiPublicWebContentRouteImport } from './routes/api/public/web-content'
import { Route as ApiPublicWaitlistRouteImport } from './routes/api/public/waitlist'
import { Route as ApiPublicPasswordResetRouteImport } from './routes/api/public/password-reset'
import { Route as ApiPublicAccountDeleteLoginRouteImport } from './routes/api/public/account-delete-login'
import { Route as ApiPublicAccountDelete2faRouteImport } from './routes/api/public/account-delete-2fa'
import { Route as ApiPublicAccountDeleteRouteImport } from './routes/api/public/account-delete'
import { Route as ApiPublicAccessRouteImport } from './routes/api/public/access'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRightsRoute = GdprRightsRouteImport.update({
  id: '/gdpr-rights',
  path: '/gdpr-rights',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteDataRoute = DeleteDataRouteImport.update({
  id: '/delete-data',
  path: '/delete-data',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityPostIdRoute = CommunityPostIdRouteImport.update({
  id: '/community/$postId',
  path: '/community/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebContentRoute = ApiPublicWebContentRouteImport.update({
  id: '/api/public/web-content',
  path: '/api/public/web-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaitlistRoute = ApiPublicWaitlistRouteImport.update({
  id: '/api/public/waitlist',
  path: '/api/public/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPasswordResetRoute = ApiPublicPasswordResetRouteImport.update({
  id: '/api/public/password-reset',
  path: '/api/public/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAccountDeleteLoginRoute =
  ApiPublicAccountDeleteLoginRouteImport.update({
    id: '/api/public/account-delete-login',
    path: '/api/public/account-delete-login',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAccountDelete2faRoute =
  ApiPublicAccountDelete2faRouteImport.update({
    id: '/api/public/account-delete-2fa',
    path: '/api/public/account-delete-2fa',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAccountDeleteRoute = ApiPublicAccountDeleteRouteImport.update({
  id: '/api/public/account-delete',
  path: '/api/public/account-delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAccessRoute = ApiPublicAccessRouteImport.update({
  id: '/api/public/access',
  path: '/api/public/access',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/delete-account': typeof DeleteAccountRoute
  '/delete-data': typeof DeleteDataRoute
  '/gdpr': typeof GdprRoute
  '/gdpr-rights': typeof GdprRightsRoute
  '/password-reset': typeof PasswordResetRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/api/public/access': typeof ApiPublicAccessRoute
  '/api/public/account-delete': typeof ApiPublicAccountDeleteRoute
  '/api/public/account-delete-2fa': typeof ApiPublicAccountDelete2faRoute
  '/api/public/account-delete-login': typeof ApiPublicAccountDeleteLoginRoute
  '/api/public/password-reset': typeof ApiPublicPasswordResetRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
  '/api/public/web-content': typeof ApiPublicWebContentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/delete-account': typeof DeleteAccountRoute
  '/delete-data': typeof DeleteDataRoute
  '/gdpr': typeof GdprRoute
  '/gdpr-rights': typeof GdprRightsRoute
  '/password-reset': typeof PasswordResetRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/api/public/access': typeof ApiPublicAccessRoute
  '/api/public/account-delete': typeof ApiPublicAccountDeleteRoute
  '/api/public/account-delete-2fa': typeof ApiPublicAccountDelete2faRoute
  '/api/public/account-delete-login': typeof ApiPublicAccountDeleteLoginRoute
  '/api/public/password-reset': typeof ApiPublicPasswordResetRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
  '/api/public/web-content': typeof ApiPublicWebContentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/delete-account': typeof DeleteAccountRoute
  '/delete-data': typeof DeleteDataRoute
  '/gdpr': typeof GdprRoute
  '/gdpr-rights': typeof GdprRightsRoute
  '/password-reset': typeof PasswordResetRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/api/public/access': typeof ApiPublicAccessRoute
  '/api/public/account-delete': typeof ApiPublicAccountDeleteRoute
  '/api/public/account-delete-2fa': typeof ApiPublicAccountDelete2faRoute
  '/api/public/account-delete-login': typeof ApiPublicAccountDeleteLoginRoute
  '/api/public/password-reset': typeof ApiPublicPasswordResetRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
  '/api/public/web-content': typeof ApiPublicWebContentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookie-policy'
    | '/cookies'
    | '/delete-account'
    | '/delete-data'
    | '/gdpr'
    | '/gdpr-rights'
    | '/password-reset'
    | '/privacy'
    | '/terms'
    | '/community/$postId'
    | '/api/public/access'
    | '/api/public/account-delete'
    | '/api/public/account-delete-2fa'
    | '/api/public/account-delete-login'
    | '/api/public/password-reset'
    | '/api/public/waitlist'
    | '/api/public/web-content'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookie-policy'
    | '/cookies'
    | '/delete-account'
    | '/delete-data'
    | '/gdpr'
    | '/gdpr-rights'
    | '/password-reset'
    | '/privacy'
    | '/terms'
    | '/community/$postId'
    | '/api/public/access'
    | '/api/public/account-delete'
    | '/api/public/account-delete-2fa'
    | '/api/public/account-delete-login'
    | '/api/public/password-reset'
    | '/api/public/waitlist'
    | '/api/public/web-content'
  id:
    | '__root__'
    | '/'
    | '/cookie-policy'
    | '/cookies'
    | '/delete-account'
    | '/delete-data'
    | '/gdpr'
    | '/gdpr-rights'
    | '/password-reset'
    | '/privacy'
    | '/terms'
    | '/community/$postId'
    | '/api/public/access'
    | '/api/public/account-delete'
    | '/api/public/account-delete-2fa'
    | '/api/public/account-delete-login'
    | '/api/public/password-reset'
    | '/api/public/waitlist'
    | '/api/public/web-content'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  CookiesRoute: typeof CookiesRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  DeleteDataRoute: typeof DeleteDataRoute
  GdprRoute: typeof GdprRoute
  GdprRightsRoute: typeof GdprRightsRoute
  PasswordResetRoute: typeof PasswordResetRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  CommunityPostIdRoute: typeof CommunityPostIdRoute
  ApiPublicAccessRoute: typeof ApiPublicAccessRoute
  ApiPublicAccountDeleteRoute: typeof ApiPublicAccountDeleteRoute
  ApiPublicAccountDelete2faRoute: typeof ApiPublicAccountDelete2faRoute
  ApiPublicAccountDeleteLoginRoute: typeof ApiPublicAccountDeleteLoginRoute
  ApiPublicPasswordResetRoute: typeof ApiPublicPasswordResetRoute
  ApiPublicWaitlistRoute: typeof ApiPublicWaitlistRoute
  ApiPublicWebContentRoute: typeof ApiPublicWebContentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset': {
      id: '/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr-rights': {
      id: '/gdpr-rights'
      path: '/gdpr-rights'
      fullPath: '/gdpr-rights'
      preLoaderRoute: typeof GdprRightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-data': {
      id: '/delete-data'
      path: '/delete-data'
      fullPath: '/delete-data'
      preLoaderRoute: typeof DeleteDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$postId': {
      id: '/community/$postId'
      path: '/community/$postId'
      fullPath: '/community/$postId'
      preLoaderRoute: typeof CommunityPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/web-content': {
      id: '/api/public/web-content'
      path: '/api/public/web-content'
      fullPath: '/api/public/web-content'
      preLoaderRoute: typeof ApiPublicWebContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/waitlist': {
      id: '/api/public/waitlist'
      path: '/api/public/waitlist'
      fullPath: '/api/public/waitlist'
      preLoaderRoute: typeof ApiPublicWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/password-reset': {
      id: '/api/public/password-reset'
      path: '/api/public/password-reset'
      fullPath: '/api/public/password-reset'
      preLoaderRoute: typeof ApiPublicPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/account-delete-login': {
      id: '/api/public/account-delete-login'
      path: '/api/public/account-delete-login'
      fullPath: '/api/public/account-delete-login'
      preLoaderRoute: typeof ApiPublicAccountDeleteLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/account-delete-2fa': {
      id: '/api/public/account-delete-2fa'
      path: '/api/public/account-delete-2fa'
      fullPath: '/api/public/account-delete-2fa'
      preLoaderRoute: typeof ApiPublicAccountDelete2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/account-delete': {
      id: '/api/public/account-delete'
      path: '/api/public/account-delete'
      fullPath: '/api/public/account-delete'
      preLoaderRoute: typeof ApiPublicAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/access': {
      id: '/api/public/access'
      path: '/api/public/access'
      fullPath: '/api/public/access'
      preLoaderRoute: typeof ApiPublicAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  CookiesRoute: CookiesRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  DeleteDataRoute: DeleteDataRoute,
  GdprRoute: GdprRoute,
  GdprRightsRoute: GdprRightsRoute,
  PasswordResetRoute: PasswordResetRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  CommunityPostIdRoute: CommunityPostIdRoute,
  ApiPublicAccessRoute: ApiPublicAccessRoute,
  ApiPublicAccountDeleteRoute: ApiPublicAccountDeleteRoute,
  ApiPublicAccountDelete2faRoute: ApiPublicAccountDelete2faRoute,
  ApiPublicAccountDeleteLoginRoute: ApiPublicAccountDeleteLoginRoute,
  ApiPublicPasswordResetRoute: ApiPublicPasswordResetRoute,
  ApiPublicWaitlistRoute: ApiPublicWaitlistRoute,
  ApiPublicWebContentRoute: ApiPublicWebContentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
